[package]
name = "visual_authoring_render_model"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
thiserror.workspace = true
visual_authoring_core_math = { path = "../core_math" }
visual_authoring_document = { path = "../document" }
visual_authoring_scene = { path = "../scene" }
